"""status of ads

Revision ID: 5b6d3e5eeb21
Revises: 621882a2cb45
Create Date: 2025-07-20 19:19:14.694741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6d3e5eeb21'
down_revision: Union[str, Sequence[str], None] = '621882a2cb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('ad', sa.Column('translated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad', 'translated')
    op.drop_column('ad', 'posted')
    # ### end Alembic commands ###
