"""Create other table

Revision ID: 621882a2cb45
Revises: 1f3cd8127946
Create Date: 2025-07-16 19:49:43.507154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621882a2cb45'
down_revision: Union[str, Sequence[str], None] = '1f3cd8127946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('account_oid', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('live_ads', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.BigInteger(), nullable=True),
    sa.Column('list_id', sa.BigInteger(), nullable=True),
    sa.Column('list_time', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('commercial_type', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('property_legal_document', sa.Integer(), nullable=True),
    sa.Column('region_v2', sa.Integer(), nullable=True),
    sa.Column('area_v2', sa.Integer(), nullable=True),
    sa.Column('ward', sa.Integer(), nullable=True),
    sa.Column('furnishing_sell', sa.Integer(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('unique_street_id', sa.String(), nullable=True),
    sa.Column('is_main_street', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('area_name', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('price_string', sa.String(), nullable=True),
    sa.Column('webp_image', sa.String(), nullable=True),
    sa.Column('number_of_images', sa.Integer(), nullable=True),
    sa.Column('ward_name', sa.String(), nullable=True),
    sa.Column('pty_map', sa.String(), nullable=True),
    sa.Column('pty_map_modifier', sa.Float(), nullable=True),
    sa.Column('thumbnail_image', sa.String(), nullable=True),
    sa.Column('size_unit_string', sa.String(), nullable=True),
    sa.Column('contain_videos', sa.Integer(), nullable=True),
    sa.Column('account_id_fk', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id_fk'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id')
    )
    op.create_table('ad_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id_fk', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('image_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id_fk'], ['ad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id_fk', sa.Integer(), nullable=True),
    sa.Column('param_id', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id_fk'], ['ad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_parameter')
    op.drop_table('ad_image')
    op.drop_table('ad')
    op.drop_table('account')
    # ### end Alembic commands ###
